* install-cm-incudine

** What does this script do?

   This script will give you an entire lisp environment from start to finish, as well as setup [[https://github.com/ormf/cm-incudine][cm-incudine]]. It has been made because I was getting tired of installing everything on all of my devices and wanted to make an effortless install method to setup cm-incudine.

** What Operating System is this for?

   install-cm-incudine is specifically designed for arch-based Linux distros. However, you can easily modify it to work with other Linux distros. Change the $INSTALL_CMD variable at the top of the script, and make sure all uses of $INSTALL_CMD are installing packages that exist on your distribution. You can also just install the packages manually.

   I would really like to have the script auto-detect which distribution you are on, and install the packages needed for cm-incudine. If you know how to do this and/or know which packages to install for a specific distro, please [[mailto:bthaleproductions@gmail.com][contact me]] or [[https://github.com/brandflake11/install-cm-incudine/pulls][submit a pull request]]. The ideal way would be to have logic in the script that would detect which distro you are on at the start of the script and then use specific packages and package manager calls for the distro in question with some kind of case or if statement. 

** What packages does this install

   From the Arch Linux repositories:
   #+BEGIN_SRC bash
   git emacs sbcl jack2 realtime-privileges portaudio portmidi libsndfile fftw gsl clthreads
   #+END_SRC
   
   and optionally:
   #+BEGIN_SRC bash
   pro-audio 
   #+END_SRC

   Nothing should be reinstalled or overwritten with the default script settings.

** What if I have issues or feedback?

   Please [[mailto:bthaleproductions@gmail.com][contact me]], make a post at [[https://github.com/brandflake11/install-cm-incudine/issues][issues]], or [[https://github.com/brandflake11/install-cm-incudine/pulls][submit a pull request]]. 

** License/Notice

   This script's code is all licensed under the GPLv3. The programs this script installs all have their own respective licenses. As a user of this script, you assume all responsibility to and damages or other happenings that may occur.
